version: "3"
services:
  confluence:
    container_name: confluence
    hostname: confluence
    image: confluence-4-testing:${CONFLUENCE_VERSION}
    build:
      context: .
      args:
          CONFLUENCE_VERSION: ${CONFLUENCE_VERSION}
          JAVA_VERSION: ${JAVA_VERSION}
    environment:
      - TZ
      - LC_ALL
      - LANG
      - LANGUAGE
      - VIRTUAL_HOST=confluence.docker
    ports:
      - "8090:8090"
      - "8092:8091"
      - "${DEBUG_PORT}:5005"
    networks:
      - confluence-net   

  jira:
    container_name: jira
    hostname: jira
    image: jira-4-testing:${JIRA_VERSION}
    build:
      context: jira/.
      args:
          JIRA_VERSION: ${JIRA_VERSION}
          JAVA_VERSION: ${JAVA_VERSION}
    environment:
      - TZ
      - LC_ALL
      - LANG
      - LANGUAGE
      - VIRTUAL_HOST=jira.docker
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ldap
    networks:
      - confluence-net

  proxy:
    container_name: http-proxy
    hostname: http-proxy
    image: codekitchen/dinghy-http-proxy
    environment:
      - DNS_IP=127.0.0.1
      - CONTAINER_NAME=http-proxy
    ports:
      - "80:80"
      - "443:443"
      - "19322:19322/udp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - confluence-net  

  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=confluence
    ports:
      - "5432:5432"
    networks:
      - confluence-net

  oracle:
    image: oskarflores/confluence-database:oracle-12c
    container_name: oracle
    hostname: oracle
    ports:
      - "1521:1521"
      - "8080:8080"
    networks:
      - confluence-net

  mysql:
    image: oskarflores/confluence-database:mysql-5.6
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    networks:
      - confluence-net

  sqlserver:
    image: oskarflores/confluence-database:sqlserver-2017
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    networks:
      - confluence-net    


  ldap:
    image: aruizca/confluence-test-ldap
    container_name: ldap
    hostname: ldap
    privileged: true
    ports:
      - "389:389"
    networks:
      - confluence-net

networks:
  confluence-net:
    driver: bridge